# Makefile for Vulnscan installation

install:
    @echo "Installing Vulnscan..."
    mkdir -p /usr/local/bin
    cp vulnscan.sh /usr/local/bin/vulnscan
    chmod +x /usr/local/bin/vulnscan
    @echo "Vulnscan installed successfully. You can now run it with the command 'vulnscan'."

uninstall:
    @echo "Uninstalling Vulnscan..."
    rm -f /usr/local/bin/vulnscan
    @echo "Vulnscan uninstalled successfully."
